// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update.sql

package user_connection

import (
	"context"
	"time"
)

const update = `-- name: Update :exec
UPDATE users
SET
    role = $2,
    email = $3,
    first_name = $4,
    last_name = $5,
    updated_at = $6
WHERE
    id = $1
`

type UpdateParams struct {
	ID        int       `json:"id"`
	Role      Roles     `json:"role"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.ID,
		arg.Role,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.UpdatedAt,
	)
	return err
}
