// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: create.sql

package user_connection

import (
	"context"
)

const create = `-- name: Create :one
INSERT INTO users
    (role, email, first_name, last_name)
VALUES
    ($1,$2,$3,$4)
RETURNING id, first_name, last_name, email, role, active, password, created_at, updated_at
`

type CreateParams struct {
	Role      Roles  `json:"role"`
	Email     string `json:"email"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (User, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Role,
		arg.Email,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
