// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_one_by_email.sql

package user_connection

import (
	"context"
)

const getOneByEmail = `-- name: GetOneByEmail :one
SELECT id, first_name, last_name, email, role, active, password, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetOneByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getOneByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
