// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_one_by_id.sql

package user_connection

import (
	"context"
)

const getOneById = `-- name: GetOneById :one
SELECT id, first_name, last_name, email, role, active, password, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetOneById(ctx context.Context, id int) (User, error) {
	row := q.db.QueryRow(ctx, getOneById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Role,
		&i.Active,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
