// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: find_one_by_code.sql

package currency_connection

import (
	"context"
)

const findOneByCode = `-- name: FindOneByCode :one
SELECT id, name, code, number, country, country_code, search_url, usd_exchange_rate, fic, created_by, updated_by, created_at, updated_at FROM currency WHERE code = $1
`

func (q *Queries) FindOneByCode(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRow(ctx, findOneByCode, code)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Number,
		&i.Country,
		&i.CountryCode,
		&i.SearchUrl,
		&i.UsdExchangeRate,
		&i.Fic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
