// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: find_one_by_id.sql

package currency_connection

import (
	"context"
)

const findOneById = `-- name: FindOneById :one
SELECT id, name, code, number, country, country_code, search_url, usd_exchange_rate, fic, created_by, updated_by, created_at, updated_at FROM currency WHERE id = $1
`

func (q *Queries) FindOneById(ctx context.Context, id int) (Currency, error) {
	row := q.db.QueryRow(ctx, findOneById, id)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Number,
		&i.Country,
		&i.CountryCode,
		&i.SearchUrl,
		&i.UsdExchangeRate,
		&i.Fic,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
