// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update.sql

package currency_connection

import (
	"context"
	"time"
)

const update = `-- name: Update :exec
UPDATE
    currency
SET
    id = $2,
    name = $3,
    code = $4,
    number = $5,
    country = $6,
    country_code = $7,
    search_url = $8,
    usd_exchange_rate = $9,
    fic = $10,
    updated_by = $11,
    updated_at = $12
WHERE
    id = $1
`

type UpdateParams struct {
	ID              int       `json:"id"`
	ID_2            int       `json:"id_2"`
	Name            string    `json:"name"`
	Code            string    `json:"code"`
	Number          *int      `json:"number"`
	Country         *string   `json:"country"`
	CountryCode     *string   `json:"country_code"`
	SearchUrl       *string   `json:"search_url"`
	UsdExchangeRate float64   `json:"usd_exchange_rate"`
	Fic             bool      `json:"fic"`
	UpdatedBy       *int      `json:"updated_by"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.Exec(ctx, update,
		arg.ID,
		arg.ID_2,
		arg.Name,
		arg.Code,
		arg.Number,
		arg.Country,
		arg.CountryCode,
		arg.SearchUrl,
		arg.UsdExchangeRate,
		arg.Fic,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}
