// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: find_all.sql

package currency_connection

import (
	"context"
)

const findAll = `-- name: FindAll :many
SELECT id, name, code, number, country, country_code, usd_exchange_rate, search_url, response_path_to_rate, fic, created_by, updated_by, created_at, updated_at FROM currency ORDER BY id
`

func (q *Queries) FindAll(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.Query(ctx, findAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Number,
			&i.Country,
			&i.CountryCode,
			&i.UsdExchangeRate,
			&i.SearchUrl,
			&i.ResponsePathToRate,
			&i.Fic,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
